### PR TITLE
Update project nature when loading ProjectModel

### PR DESCRIPTION
**Pull request by sratz**
Just like when the config is changed in the project property page.

### CODE REVIEW

**Comment by acanda** [comment]
Thank you for your contribution. I'm not sure I understand what the goal of this change is. Do you want to automatically enable/disable PMD when someone manually changes the .eclipse-pmd configuration file?

**Comment by sratz** [comment]
I made this change alongside #46.

The intention was to make sure the local builder configuration gets updated when updating the project from SCM.

But in fact, this is only an issue if `.project` itself is not under version control.

So I guess this change is not really necessary.

**Comment by sratz** [comment]
On second thought: There still remains an issue.

Without this change, PMD error markers don't get removed on a `git pull` that disables PMD for that project.

This is because
````
MarkerUtil.removeAllMarkers(project);
````

is called in `PMDNature.removeFrom()`.

I think this should be moved to `WorkspaceChangeListener.removeProject()`

**Comment by sratz** [comment]
I'm closing this. I don't think it's reasonable to do this implicitly.

If `.project` is under version control, that file will be updated alongside anyways.

About the marker removal: I think that's a general eclipse problems, that markers which were created by a builder that is not active anymore, don't get removed automatically.

**Pull request closed without merging**
