### PR TITLE
Builder improvements

### PR DESCRIPTION
**Pull request by sratz**
Builder: Don't manually recurse into subfolders.
ResourceDelta.accept() and Resource.accept() alrady take care of
recursing into all needed children.

Otherwise, every ever so little change would cause a full rescan
of every file in the project.

This looks like it was accidentally introduced in
7e21a1a22ae9ac124d910490027a650d84c95f06.

Also improve user feedback by listing the files currently being processed in the progress.

### CODE REVIEW

**Comment by acanda** [comment]
Manually recursing into subfolders wasn't accidentally introduced. eclipse-pmd ignores files in folders marked as 'derived'. When you remove this attribute from a folder you need to analyse each file in this folder and its subfolders.

I like the improved progress reporting though and will cherry pick this commit into master.

**Comment by sratz** [comment]
Hm, right.

However, in the case without any derived files that change has a *huge* performance impact, because now, if file `/project/folder/subfolder/somefile` changes, *all* the files in `/project/folder` are re-analyzed.

While technically, this is only necessary if the `derived` attribute of `/project/folder` has actually been removed.

Moreover, this is actually done multiple times: The DeltaVisitor always returns `true`, so in this case, the framework recurses into `/project/folder/subfolder` and then all files in there are re-analyzed again, resulting in a large cascade for folder hierarchies.

Is it possible to check for `derived` attribute changes in the `IResourceDelta`?

**Comment by acanda** [comment]
You are right. That change has a huge performance impact. Luckily there is `IResourceDelta.getFlags()` and a `DERIVED_CHANGED` flag. When I check this flag and only recurse when the flag is set then only the changed files are analysed and even better: only once.

I have to test this a little bit more as there are some corner cases like the PMD rule PackageCase. This rule checks the package names and could potentially fire for a lot of files when renaming a package (i.e. folder).

But thank you for pointing this out. This will be a huge improvement when working on big projects.

**Comment by sratz** [comment]
Closing this, since progress reporting improvement is merged to master and the performance bug is fixed.

**Pull request closed without merging**
